# Generated by Django 5.0.1 on 2024-02-17 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.TextField()),
                ('title_ru', models.TextField()),
                ('title_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/filial_message/images')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userprofile')),
            ],
            options={
                'verbose_name': 'Filial text',
                'verbose_name_plural': 'Filial text',
            },
        ),
        migrations.CreateModel(
            name='RegionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.TextField()),
                ('title_ru', models.TextField()),
                ('title_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/region_message/images')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userprofile')),
            ],
            options={
                'verbose_name': 'Region text',
                'verbose_name_plural': 'Region text',
            },
        ),
        migrations.CreateModel(
            name='StartMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.TextField()),
                ('title_ru', models.TextField()),
                ('title_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/start_message/images')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userprofile')),
            ],
            options={
                'verbose_name': 'Bosh sahifa matni',
                'verbose_name_plural': 'Home text',
            },
        ),
        migrations.CreateModel(
            name='VacancyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.TextField()),
                ('title_ru', models.TextField()),
                ('title_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/vacancy_message/images')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userprofile')),
            ],
            options={
                'verbose_name': 'Vacancy text',
                'verbose_name_plural': 'Vacancy text',
            },
        ),
    ]
