# Generated by Django 5.0.1 on 2024-02-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.TextField()),
                ('title_ru', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/start_message/images')),
            ],
            options={
                'verbose_name': 'Bosh sahifa matni',
                'verbose_name_plural': 'Bosh sahifa matni',
            },
        ),
    ]
