# Generated by Django 5.0.1 on 2024-02-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startmessage',
            name='title_en',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='startmessage',
            name='title_ru',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='startmessage',
            name='title_uz',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
