# Generated by Django 5.0.1 on 2024-02-04 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_initial'),
        ('content', '0002_startmessage_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startmessage',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userprofile'),
        ),
    ]
