# Generated by Django 5.0.1 on 2024-02-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_mainofficevacancymessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainofficevacancymessage',
            options={'verbose_name': 'Main office vacancy text', 'verbose_name_plural': 'Main office vacancy text'},
        ),
    ]
