# Generated by Django 5.0.1 on 2024-02-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_startmessage_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startmessage',
            name='title_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startmessage',
            name='title_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
