# Generated by Django 5.0.1 on 2024-02-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_regionmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionmessage',
            options={'verbose_name': 'Region text', 'verbose_name_plural': 'Region text'},
        ),
    ]
