# Generated by Django 5.0.1 on 2024-02-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user_profile',
        ),
    ]
