# Generated by Django 5.0.1 on 2024-02-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='wage_expectation',
            field=models.CharField(blank=True, default=0, max_length=128, null=True),
        ),
    ]
