# Generated by Django 5.0.1 on 2024-02-06 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_userprofile_bot_username'),
        ('company', '0002_remove_company_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='company.region'),
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=128)),
                ('name_ru', models.CharField(blank=True, max_length=128, null=True)),
                ('name_en', models.CharField(blank=True, max_length=128, null=True)),
                ('opened_date', models.DateTimeField(auto_now=True)),
                ('closed_date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.region')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_filial', to='bot.userprofile')),
            ],
        ),
    ]
