# Generated by Django 5.0.1 on 2024-02-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_vacancy_filial_vacancy_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='filial',
            field=models.ManyToManyField(related_name='vacancy_filial', to='company.filial'),
        ),
    ]
