# Generated by Django 5.0.1 on 2024-02-06 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_region_parent_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
