# Generated by Django 5.0.1 on 2024-02-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_region_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='parent',
        ),
    ]
