# Generated by Django 5.0.1 on 2024-02-19 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_vacancy_main_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='filial',
            field=models.ManyToManyField(blank=True, null=True, related_name='vacancy_filial', to='company.filial'),
        ),
    ]
