# Generated by Django 5.0.1 on 2024-02-07 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_region_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='company',
        ),
        migrations.AlterField(
            model_name='filial',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
