# Generated by Django 5.0.1 on 2024-02-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_region_company_alter_filial_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='user_profile',
        ),
    ]
