# Generated by Django 5.0.1 on 2024-02-20 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_vacancy_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatelanguages',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_language_vacancy', to='company.vacancy'),
        ),
    ]
