# Generated by Django 5.0.1 on 2024-02-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_candidatelanguages_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='created_at',
        ),
        migrations.AddField(
            model_name='candidate',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
