# Generated by Django 5.0.1 on 2024-02-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_remove_candidate_created_at_candidate_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education_data',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='language_data',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='candidatelanguages',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
