# Generated by Django 5.0.1 on 2024-02-24 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_userbot_answer_userbot_q_number_userbot_question_and_more'),
        ('company', '0011_candidate_education_data_candidate_language_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.BooleanField(default=False)),
                ('last_name', models.BooleanField(default=False)),
                ('middle_name', models.BooleanField(default=False)),
                ('gender', models.BooleanField(default=False)),
                ('birthday', models.BooleanField(default=False)),
                ('image', models.BooleanField(default=False)),
                ('main_phone', models.BooleanField(default=False)),
                ('extra_phone', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('address', models.BooleanField(default=False)),
                ('legal_address', models.BooleanField(default=False)),
                ('wage_expectation', models.BooleanField(default=False)),
                ('node', models.BooleanField(default=False)),
                ('education', models.BooleanField(default=False)),
                ('language_data', models.BooleanField(default=False)),
                ('education_data', models.BooleanField(default=False)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_user_resume_filter', to='bot.userbot')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_resume_filter', to='bot.userprofile')),
            ],
        ),
    ]
