# Generated by Django 5.0.1 on 2024-02-24 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_userbot_answer_userbot_q_number_userbot_question_and_more'),
        ('company', '0012_resumefilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumefilter',
            name='bot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_user_resume_filter', to='bot.userbot'),
        ),
    ]
