# Generated by Django 5.0.1 on 2024-02-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_resumefilter_bot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumefilter',
            name='education_data',
        ),
        migrations.RemoveField(
            model_name='resumefilter',
            name='language_data',
        ),
    ]
