# Generated by Django 5.0.1 on 2024-02-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_remove_resumefilter_education_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefilter',
            name='language',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='candidatelanguages',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resumefilter',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
