# Generated by Django 5.0.1 on 2024-02-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_candidatelanguages_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='node',
            new_name='note',
        ),
    ]
