# Generated by Django 5.0.1 on 2024-02-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_rename_node_candidate_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumefilter',
            old_name='node',
            new_name='note',
        ),
    ]
