# Generated by Django 5.0.1 on 2024-03-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_rename_node_resumefilter_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumefilter',
            name='bot_user',
        ),
    ]
