# Generated by Django 5.0.1 on 2024-03-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_remove_resumefilter_bot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='image',
            field=models.ImageField(default=1, upload_to='static/filials/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filial',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filial',
            name='title_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filial',
            name='title_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filial',
            name='title_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(default=1, upload_to='static/regions/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='title_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='title_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='title_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filial',
            name='name_en',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filial',
            name='name_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
