# Generated by Django 5.0.1 on 2024-03-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_filial_image_filial_order_filial_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'vacancys', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/vacancies/images'),
        ),
    ]
