# Generated by Django 5.0.1 on 2024-03-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_alter_vacancy_options_vacancy_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='resumefilter',
            name='full_name',
            field=models.BooleanField(default=False),
        ),
    ]
