# Generated by Django 5.0.1 on 2024-03-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_candidate_full_name_resumefilter_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumefilter',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='resumefilter',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='resumefilter',
            name='middle_name',
        ),
    ]
