# Generated by Django 5.0.1 on 2024-03-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_remove_resumefilter_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='name_en',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
