# Generated by Django 5.0.1 on 2024-03-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_alter_vacancy_name_en_alter_vacancy_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='integration_code',
            field=models.IntegerField(default=0),
        ),
    ]
