# Generated by Django 5.0.1 on 2024-03-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_region_integration_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='chat_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='test_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='test_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_integration_code',
            field=models.IntegerField(default=0),
        ),
    ]
