# Generated by Django 5.0.1 on 2024-05-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_alter_filial_image_alter_region_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='job_integration_code',
            field=models.IntegerField(default=0),
        ),
    ]
