# Generated by Django 5.0.1 on 2024-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_vacancy_job_integration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='job_integration_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_integration_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
