# Generated by Django 5.0.1 on 2024-02-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('full_name', models.CharField(blank=True, max_length=128, null=True)),
                ('passport', models.IntegerField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('inline_type', models.CharField(blank=True, max_length=100, null=True)),
                ('new_employee', models.BooleanField(default=False)),
                ('old_employee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UserBot',
                'verbose_name_plural': 'Bot Users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=128)),
            ],
        ),
    ]
