# Generated by Django 5.0.1 on 2024-02-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_initial'),
        ('company', '0002_remove_company_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='bot',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
