# Generated by Django 5.0.1 on 2024-02-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_bot_user_profile_bot_company'),
        ('company', '0002_remove_company_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
