# Generated by Django 5.0.1 on 2024-02-21 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_userbot_candidate_language'),
        ('main', '0005_remove_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.answer'),
        ),
        migrations.AddField(
            model_name='userbot',
            name='q_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbot',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
        migrations.AddField(
            model_name='userbot',
            name='true_count',
            field=models.IntegerField(default=0),
        ),
    ]
