# Generated by Django 5.0.1 on 2024-02-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_userbot_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbot',
            name='new_employee',
        ),
        migrations.RemoveField(
            model_name='userbot',
            name='old_employee',
        ),
    ]
