# Generated by Django 5.0.1 on 2024-02-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_userbot_new_employee_and_more'),
        ('company', '0002_remove_company_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bot',
            new_name='BotToken',
        ),
    ]
