# Generated by Django 5.0.1 on 2024-02-26 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_userbot_resume_filter'),
        ('main', '0011_remove_writtenquestion_vacancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='write_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.writtenanswer'),
        ),
        migrations.AddField(
            model_name='userbot',
            name='write_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbot',
            name='write_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.writtenquestion'),
        ),
    ]
