# Generated by Django 5.0.1 on 2024-03-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_userbot_write_answer_userbot_write_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='language_filter',
            field=models.IntegerField(default=0),
        ),
    ]
