# Generated by Django 5.0.1 on 2024-02-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_userbot_bot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bot_username',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
