# Generated by Django 5.0.1 on 2024-02-07 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_userprofile_bot_username'),
        ('company', '0005_alter_region_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.filial'),
        ),
        migrations.AddField(
            model_name='userbot',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.region'),
        ),
    ]
