# Generated by Django 5.0.1 on 2024-02-20 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_userbot_candidate_language'),
        ('company', '0007_alter_vacancy_company_alter_vacancy_filial'),
        ('main', '0003_alter_answer_user_profile_alter_answer_vacancy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.TextField()),
                ('title_ru', models.TextField()),
                ('title_en', models.TextField()),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='static/about_company/videos')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/about_company/images')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, max_length=300, null=True)),
                ('facebook', models.URLField(blank=True, max_length=300, null=True)),
                ('telegram', models.URLField(blank=True, max_length=300, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.URLField(blank=True, max_length=300, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userprofile')),
            ],
        ),
    ]
