# Generated by Django 5.0.1 on 2024-02-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutcompany_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
