# Generated by Django 5.0.1 on 2024-02-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_failedcandidate_successcandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedcandidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/failed_candidate/images'),
        ),
        migrations.AlterField(
            model_name='successcandidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/success_candidate/images'),
        ),
    ]
