# Generated by Django 5.0.1 on 2024-02-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_failedcandidate_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failedcandidate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='successcandidate',
            name='created_at',
        ),
        migrations.AddField(
            model_name='failedcandidate',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='successcandidate',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
