# Generated by Django 5.0.1 on 2024-02-26 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_resumefilter_language_alter_candidate_add_date_and_more'),
        ('main', '0011_remove_writtenquestion_vacancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writtenanswer',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.candidate'),
            preserve_default=False,
        ),
    ]
