# Generated by Django 5.0.1 on 2024-02-28 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_candidatelanguages_company_and_more'),
        ('main', '0013_education_user_profile_education_vacancy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='language',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='languagelevel',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='education',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='language',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
