# Generated by Django 5.0.1 on 2024-02-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_education_vacancy_remove_language_vacancy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='successcandidate',
            old_name='node',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='failedcandidate',
            name='node',
        ),
        migrations.AddField(
            model_name='failedcandidate',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
