# Generated by Django 5.0.1 on 2024-03-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_node_successcandidate_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='youtube',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
