# Generated by Django 5.0.1 on 2024-03-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_contact_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='language',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
