# Generated by Django 5.0.1 on 2024-03-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_answer_order_language_order_languagelevel_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
