# Generated by Django 5.0.1 on 2024-03-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_education_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writtenanswer',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='writtenquestion',
            name='vacancy',
        ),
    ]
