# Generated by Django 5.0.1 on 2024-03-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_alter_vacancy_name_en_alter_vacancy_name_ru'),
        ('main', '0019_remove_writtenanswer_vacancy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='question',
            name='vacancy',
            field=models.ManyToManyField(to='company.vacancy'),
        ),
    ]
