# Generated by Django 5.0.1 on 2024-03-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_writtenquestion_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='integration_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='integration_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='integration_code',
            field=models.IntegerField(default=0),
        ),
    ]
