# Generated by Django 5.0.1 on 2024-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_education_integration_code_language_integration_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writtenanswer',
            old_name='title_en',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='writtenanswer',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='writtenanswer',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='writtenanswer',
            name='integration_code',
            field=models.IntegerField(default=0),
        ),
    ]
