# Generated by Django 5.0.1 on 2024-03-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_integration_code_writtenanswer_write_integration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writtenanswer',
            name='write_integration_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
